alias g="git"
alias s="g status"
alias cdc="cd CelesteEngine/ && g s"
alias cdu="cd .."
alias pall="g pull && cd CelesteEngine/ && g pull && cd .."
alias sub="g pull && g push"
alias celup="g add CelesteEngine && g commit -m\"Updating submodule\" && sub"
alias remorig="find . -name \"*.orig\" -type f -delete"
alias resfile="!f() { filetype=${1}; g checkout -- $filetype;  }; f"
alias dfile="!f() { filetype=${1}; g diff -- $filetype;  }; f"
alias al="g add ."
alias cal="!f() { message=${1}; al && g commit -m $message;  }; f"